- name: Install
  hosts: all
  become: yes
  tasks:
  - name: install docker
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

  - name: ensure docker registry is available
    apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present
  - name: ensure docker and dependencies are installed
    apt: name=docker-ce update_cache=yes
  - name: run docker-compose
    apt: name=docker-compose update_cache=yes
  - name: Create and start services
    docker_compose:
      project_src: /task/ 
   